package homework7;

import javax.swing.*;
import java.awt.*;
import java.util.HashSet;

public class _15211301_WeiXiao_7_UPdateStrategyUI extends javax.swing.JFrame
{
    /* The controller "pointer" */
    _15211301_WeiXiao_7_Controll controller = _15211301_WeiXiao_7_Controll.getInstance();

    /**
     * Creates new form AddBookUI
     */
    public _15211301_WeiXiao_7_UPdateStrategyUI(String ID) {
        initComponents(ID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String ID) {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bCancel = new javax.swing.JButton();
        bSubmit = new javax.swing.JButton();
        tType = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tParas = new javax.swing.JTextField();
        Sunxiaoyu0 = new javax.swing.JCheckBox();
        Sunxiaoyu1 = new javax.swing.JCheckBox();
        Sunxiaoyu2 = new javax.swing.JCheckBox();
        Sunxiaoyu3 = new javax.swing.JCheckBox();
        Sunxiaoyu4 = new javax.swing.JCheckBox();

        lID = new javax.swing.JLabel(ID);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(450, 520));
        Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(0, size.height / 2 - 300);

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        jLabel1.setText("策略编号：");
        jLabel1.setSize(new java.awt.Dimension(0, 80));

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        jLabel2.setText("策略名称：");
        jLabel2.setSize(new java.awt.Dimension(0, 80));

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        jLabel3.setText("策略类型：");
        jLabel3.setSize(new java.awt.Dimension(0, 80));

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        jLabel4.setText("适用书籍：");
        jLabel4.setSize(new java.awt.Dimension(0, 80));

        tName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 48)); // NOI18N
        jLabel5.setText("更新策略");

        bCancel.setFont(new java.awt.Font("Microsoft Tai Le", 0, 13)); // NOI18N
        bCancel.setText("取消");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        bSubmit.setFont(new java.awt.Font("Microsoft Tai Le", 0, 13)); // NOI18N
        bSubmit.setText("提交");
        bSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubmitActionPerformed(evt);
            }
        });

        tType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "绝对值优惠策略", "百分比优惠策略", "顾客最优策略", " " }));
        tType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTypeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 13)); // NOI18N
        jLabel6.setText("参数：");
        jLabel6.setSize(new java.awt.Dimension(0, 80));

        tParas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tParasActionPerformed(evt);
            }
        });

        Sunxiaoyu0.setText("非教材计算机");
        Sunxiaoyu0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sunxiaoyu0ActionPerformed(evt);
            }
        });

        Sunxiaoyu1.setText("教材类");
        Sunxiaoyu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sunxiaoyu1ActionPerformed(evt);
            }
        });

        Sunxiaoyu2.setText("连环画");
        Sunxiaoyu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sunxiaoyu2ActionPerformed(evt);
            }
        });

        Sunxiaoyu3.setText("养生类");
        Sunxiaoyu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sunxiaoyu3ActionPerformed(evt);
            }
        });

        Sunxiaoyu4.setText("其他");
        Sunxiaoyu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sunxiaoyu4ActionPerformed(evt);
            }
        });

        lID.setFont(new java.awt.Font("Microsoft Tai Le", 0, 13)); // NOI18N
        lID.setText(ID);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(tName, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tParas, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(Sunxiaoyu0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(Sunxiaoyu2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(Sunxiaoyu3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(Sunxiaoyu1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(Sunxiaoyu4))
                                                                .addGap(6, 6, 6)))
                                                .addGap(50, 50, 50))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(89, 89, 89)
                                                .addComponent(lID)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(bSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(38, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lID))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(13, 13, 13)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tParas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(108, 108, 108))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(tName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(13, 13, 13)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(Sunxiaoyu0)
                                                                .addGap(5, 5, 5)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(Sunxiaoyu2)
                                                                        .addComponent(Sunxiaoyu3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(Sunxiaoyu4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(Sunxiaoyu1))
                                                .addGap(105, 105, 105)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(bCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(bSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(36, 36, 36))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNameActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCancelActionPerformed

    private void bSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubmitActionPerformed
        try{
            String ID = lID.getText();
            String name = tName.getText();
            HashSet<Integer> books = new HashSet<Integer>();
            String paras = tParas.getText();
            int type = tType.getSelectedIndex();

            if (Sunxiaoyu0.isSelected()) books.add(_15211301_WeiXiao_7_ProductSpecification.NoComputerBook);
            if (Sunxiaoyu1.isSelected()) books.add(_15211301_WeiXiao_7_ProductSpecification.TextBook);
            if (Sunxiaoyu2.isSelected()) books.add(_15211301_WeiXiao_7_ProductSpecification.ComicBook);
            if (Sunxiaoyu3.isSelected()) books.add(_15211301_WeiXiao_7_ProductSpecification.DietBook);
            if (Sunxiaoyu4.isSelected()) books.add(_15211301_WeiXiao_7_ProductSpecification.Other);

            controller.updateStrategy(type, paras, books, ID, name);

            System.out.println(_15211301_WeiXiao_7_PricingStrategyFactory.getInstance().getPricingStrategy(ID));
            JOptionPane.showMessageDialog(null, "修改成功！", "成功", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "错误", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_bSubmitActionPerformed

    private void tTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTypeActionPerformed

    private void tParasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tParasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tParasActionPerformed

    private void Sunxiaoyu0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sunxiaoyu0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sunxiaoyu0ActionPerformed

    private void Sunxiaoyu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sunxiaoyu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sunxiaoyu1ActionPerformed

    private void Sunxiaoyu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sunxiaoyu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sunxiaoyu2ActionPerformed

    private void Sunxiaoyu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sunxiaoyu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sunxiaoyu3ActionPerformed

    private void Sunxiaoyu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sunxiaoyu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sunxiaoyu4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(_15211301_WeiXiao_7_UPdateStrategyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(_15211301_WeiXiao_7_UPdateStrategyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(_15211301_WeiXiao_7_UPdateStrategyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(_15211301_WeiXiao_7_UPdateStrategyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new _15211301_WeiXiao_7_UPdateStrategyUI("123").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Sunxiaoyu0;
    private javax.swing.JCheckBox Sunxiaoyu1;
    private javax.swing.JCheckBox Sunxiaoyu2;
    private javax.swing.JCheckBox Sunxiaoyu3;
    private javax.swing.JCheckBox Sunxiaoyu4;
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lID;
    private javax.swing.JTextField tName;
    private javax.swing.JTextField tParas;
    private javax.swing.JComboBox<String> tType;
    // End of variables declaration//GEN-END:variables
}



